[versions]
compose = "1.9.3"
jdk = "23"
kotlin = "2.2.21"
kotlinx-serialization = "1.9.0"
ktor = "3.3.2"
markdown = "0.38.1"
mordant = "3.0.2"
xmlutil = "0.91.3"

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.2" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }

[libraries]
clikt = "com.github.ajalt.clikt:clikt:5.0.3"
compose-markdown = { module = "com.mikepenz:multiplatform-markdown-renderer", version.ref = "markdown" }
compose-markdown-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdown" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
eithernet = "com.slack.eithernet:eithernet:2.0.0"
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinx-serialization" }
kotlinx-serialization-xml-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
kotlinx-serialization-xml-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }
ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-engine-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-engine-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
mordant-coroutines = { module = "com.github.ajalt.mordant:mordant-coroutines", version.ref = "mordant" }
mordant-markdown = { module = "com.github.ajalt.mordant:mordant-markdown", version.ref = "mordant" }
okhttp = "com.squareup.okhttp3:okhttp:5.3.1"
okio = "com.squareup.okio:okio:3.16.4"
slf4jNop = "org.slf4j:slf4j-nop:2.0.17"
tikxml-htmlescape = "com.tickaroo.tikxml:converter-htmlescape:0.8.15"
